platform: linux
image_resource:
  type: docker-image
  source: {repository: frekele/gradle}
inputs:
- name: source_code
outputs:
- name: artifacts

run:
    path: sh
     args:
     - -exc
     - |
     cd source_code
     gradle clean assemble
     cp build/libs/*.jar ../artifacts/
