---
resources:
- name: source_code
  type: git
  source:
    uri: https://github.com/coxcs1/spring.git
- name: deploy_cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: coxcs1@etsu.edu
    password: Dog.Bark1();
    organization: coxcs1-org
    space: development
    skip_cert_check: true
jobs:
- name: common-image-build
  serial: true
  plan:
  - get: {source_code/ci, trigger: true}
  - task: build
    privileged: true
    file: source_code/ci/build.yml
  - put: deploy_cf
    params:
     manifest: source_code/ci/manifest.yml
     path: artifacts/*.jar