resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/coxcs1/spring.git
- name: deploy-cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: coxcs1@etsu.edu
    password: Dog.Bark1();
    organization: coxcs1-organization
    space: development
    skip_cert_check: true
jobs:
- name: build-cf
  serial: true
  plan:
  - {get: source-code, trigger: true}
  - task: build
    privileged: true
    file: source-code/ci/build.yml
  - put: deploy-cf
    params:
      manifest: source-code/manifest.yml
      path: artifacts/*.jar