resources:
  - name: source_code
    type: git
    source:
      uri: https://github.com/coxcs1/springbootapp.git
    
  - name: deploy_cf
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: coxcs1@etsu.edu
      password: Dog.Bark1();
      organization: coxcs1-org
      space: development

jobs:
- name: deploy-to
  public: true
  plan:
    - {get: source_code, trigger: true}
    - task: build
      privileged: true
      file: build.yml
    - put: deploy_cf
      params:
        manifest: manifest.yml
        path: artifacts/*.jar
