platform: linux

image_resource:
  type: docker-image
  source:
   repository: frekele/gradle
  
inputs:
 - name: source_code
  
outputs:
 - name: artifacts
 
run:
 user: root
 path:  source_code/ci/build.sh