platform: linux

image_resource:
  type: docker-image
  source:
   repository: gradle
  
inputs:
 - name: source-code
outputs:
 - name: artifacts
 
run:
 user: root
  path: sh
  args:
  - -exc
  - |
  gradle --stacktrace build
  cp build/libs/*.jar ../artifacts/